### ISSUE TITLE
mongodb-level is not published to Level/awesome

### ISSUE THREAD

**Issue by almereyda** [tinacms/mongodb-level#1]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Level/awesome has a list of stores, which is already a bit aged.

Adding `tinacms/mongodb-level` could bring in some fresh air.

### Reproduction

https://github.com/Level/awesome/#stores

### System Info

```shell
Reading through GitHub, trying to understand how to self-host TinaCMS + data layer, eventually on GitLab, but at least with own authorization.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/tinacms/mongodb-level/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
cc @kldavis4

**Comment by kldavis4** [comment]
I'm well aware.. I've been waiting on someone to approve this other one for many months: https://github.com/Level/awesome/pull/57

Also, I didn't want to submit this until the full test suite is passing (#10)
